ORDER = 'ORDER'
CHAOS = 'CHAOS'

WIZARD = 'WIZARD'
HERO = 'HERO'
MONSTER = 'MONSTER'
PRIEST = 'PRIEST'
TOTEM = 'TOTEM'

CELESTIAL = 'CELESTIAL'
TZEENTCH = 'TZEENTCH'
EVERCHOSEN = 'EVERCHOSEN'

HUMAN = 'HUMAN'
DAEMON = 'DAEMON'
GOR = 'GOR'
MORTAL = 'MORTAL'
