SELF_NUMBERS = 'self_numbers'
WOUNDS = 'wounds'
CHARGING = 'charging'

TOWOUND_MOD_ON_CRIT_HIT = 'towound mod on crit hit'
BONUS_REND = 'bonus rend'
CRIT_BONUS_REND = 'crit bonus rend'
MW_ON_WOUND_CRIT = 'mortal wound on towound crit'
MW_ON_HIT_CRIT = 'mortal wound on tohit crit'
EXTRA_WOUND_ON_CRIT = 'extra wound on crit'
EXTRA_HIT_ON_CRIT = 'extra hit on crit'
